name: Build and Push
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"

env:
  IMAGE_BASE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Identify current Dockerfile version
        run: |
          API_URL="https://api.github.com/repos/actions/runner/releases/latest"
          RELEASE_INFO=$(curl -s "$API_URL") # Fetch the latest release information from GitHub API
          LATEST_VERSION=$(echo "$RELEASE_INFO" | jq -r '.tag_name' | sed -E 's/[^0-9.]//g' | grep -E '^[0-9]+\.[0-9]+\.[0-9]+')
          echo "Latest version is : ${LATEST_VERSION}"
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image to both Dockerhub and GHCR
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          provenance: false
          push: true
          tags: |
            ${{ env.IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:latest
            ${{ env.IMAGE_BASE_NAME }}:${{ env.LATEST_VERSION }}
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:${{ env.LATEST_VERSION }}
