name: Build and Push
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "README.md"

env:
  IMAGE_BASE_NAME: ${{ github.repository }}

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Identify current Dockerfile version
        run: |
          DOCKERHUB_REPO="myoung34/github-runner"
          IMAGE_INFO=$(curl -s "https://hub.docker.com/v2/repositories/${DOCKERHUB_REPO}/tags")
          LATEST_VERSION=($(echo "$IMAGE_INFO" | jq -r '.results[].name' | sort -V))
          echo "Latest version of ${DOCKERHUB_REPO}: ${LATEST_VERSION}"
          echo "LATEST_VERSION" >> $GITHUB_ENV
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push image to both Dockerhub and GHCR
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          provenance: false
          push: true
          tags: |
            ${{ env.IMAGE_BASE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:latest
            ${{ env.IMAGE_BASE_NAME }}:${{ env.LATEST_VERSION }}
            ghcr.io/${{ env.IMAGE_BASE_NAME }}:${{ env.LATEST_VERSION }}